'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { randomUUID } = require('node:crypto');
const { createApp } = require('../server.cjs');
const { createStore, createSeed, validState } = require('../storage.cjs');
const engine = require('../engine.js');
const ROOT = path.resolve(__dirname, '.tmp'), SEED = createSeed();
function safeRemove(target) { const resolved = path.resolve(target); if (!(resolved === ROOT || resolved.startsWith(`${ROOT}${path.sep}`))) throw new Error('Limpieza fuera de test/.tmp rechazada.'); if (!fs.existsSync(resolved)) return; for (const entry of fs.readdirSync(resolved, { withFileTypes: true })) { const child = path.join(resolved, entry.name); if (entry.isDirectory()) safeRemove(child); else fs.unlinkSync(child); } fs.rmdirSync(resolved); }
function testDir(label) { fs.mkdirSync(ROOT, { recursive: true }); const dir = path.join(ROOT, `${label}-${randomUUID()}`); fs.mkdirSync(dir); return dir; }
async function withServer(label, run) { const dir = testDir(label), server = createApp({ dataDir: dir }); await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); }); const port = server.address().port, base = `http://127.0.0.1:${port}`; const request = async (url, options = {}) => { const response = await fetch(`${base}${url}`, { ...options, headers: { ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(options.headers || {}) } }); let body; try { body = await response.json(); } catch { body = {}; } return { status: response.status, body, headers: response.headers }; }; try { await run({ request, dir, port }); } finally { await new Promise(resolve => server.close(resolve)); safeRemove(dir); if (fs.existsSync(ROOT) && fs.readdirSync(ROOT).length === 0) fs.rmdirSync(ROOT); } }
const post = body => ({ method: 'POST', body: JSON.stringify(body) });
function badHost(port) { return new Promise((resolve, reject) => { const req = http.request({ hostname: '127.0.0.1', port, path: '/api/state', headers: { Host: 'localhost:4327' } }, res => { res.resume(); res.on('end', () => resolve(res.statusCode)); }); req.on('error', reject); req.end(); }); }
const profileBody = (name = 'Perfil test') => ({ nombre: name, objetivoHoraCent: 1500, maxMinutosEfectivosSemana: 2400, maxDesplazamientoDia: 45, pesos: { economia: 30, tiempo: 25, estabilidad: 20, flexibilidad: 15, accesibilidad: 10 } });
const offerBody = perfilId => ({ perfilId, empresa: 'Empresa test', puesto: 'Puesto test', ubicacion: 'Madrid', modalidad: 'hibrida', tipoRemuneracion: 'anual', importeCent: 3000000, pagasAnuales: 12, minutosPagadosSemana: 2400, minutosNoRemuneradosSemana: 120, diasPresenciales: 2, minutosDesplazamientoDia: 40, costeDesplazamientoDiaCent: 350, costesFijosMensualesCent: 2500, estabilidad: 4, flexibilidad: 4, accesibilidad: 3, fechaLimite: null, estado: 'activa', notas: 'Datos de prueba' });

test('1. seed, estado y seguridad HTTP', async () => withServer('state', async ({ request, port }) => { const r = await request('/api/state'); assert.equal(r.status, 200); assert.equal(r.body.perfiles.length, 1); assert.equal(r.body.ofertas.length, 3); assert.equal(r.body.candidaturas.length, 2); assert.ok(r.body.analytics.calculations.length === 3); assert.match(r.headers.get('content-security-policy'), /default-src 'self'/); assert.equal(r.headers.get('x-frame-options'), 'DENY'); assert.equal(r.headers.get('x-content-type-options'), 'nosniff'); assert.equal(await badHost(port), 403); assert.equal((await request('/api/perfiles', { method: 'POST', body: '{}', headers: { 'Content-Type': 'text/plain' } })).status, 415); assert.equal((await request('/api/perfiles', { method: 'POST', body: JSON.stringify({ nombre: 'x', relleno: 'z'.repeat(300000) }) })).status, 413); }));

test('2. CRUD de perfiles y pesos', async () => withServer('profiles', async ({ request }) => { let r = await request('/api/perfiles', post(profileBody())); assert.equal(r.status, 201); const id = r.body.id; r = await request(`/api/perfiles/${id}`, { method: 'PATCH', body: JSON.stringify({ nombre: 'Perfil editado' }) }); assert.equal(r.body.nombre, 'Perfil editado'); assert.equal((await request(`/api/perfiles/${id}`)).status, 200); const bad = profileBody('Mal'); bad.pesos.economia = 31; assert.equal((await request('/api/perfiles', post(bad))).status, 400); assert.equal((await request(`/api/perfiles/${id}`, { method: 'DELETE' })).status, 200); }));

test('3. CRUD de ofertas y cálculo REST', async () => withServer('offers', async ({ request }) => { const state = (await request('/api/state')).body; let r = await request('/api/ofertas', post(offerBody(state.perfiles[0].id))); assert.equal(r.status, 201); const id = r.body.id; r = await request(`/api/ofertas/${id}/calculo`); assert.equal(r.status, 200); assert.equal(r.body.monthlyGrossCent, 250000); assert.ok(r.body.totalScore >= 0 && r.body.totalScore <= 100); r = await request(`/api/ofertas/${id}`, { method: 'PATCH', body: JSON.stringify({ modalidad: 'remota', diasPresenciales: 0 }) }); assert.equal(r.body.modalidad, 'remota'); assert.equal((await request(`/api/ofertas/${id}`, { method: 'PATCH', body: JSON.stringify({ color: 'verde' }) })).status, 400); assert.equal((await request(`/api/ofertas/${id}`, { method: 'DELETE' })).status, 200); }));

test('4. CRUD de candidaturas sin saltarse transiciones', async () => withServer('candidates', async ({ request }) => { const state = (await request('/api/state')).body, offer = state.ofertas[1]; let r = await request('/api/candidaturas', post({ ofertaId: offer.id, proximaAccion: 'Enviar CV', proximaAccionFecha: '2026-10-01' })); assert.equal(r.status, 201); assert.equal(r.body.estado, 'borrador'); const id = r.body.id; r = await request(`/api/candidaturas/${id}`, { method: 'PATCH', body: JSON.stringify({ proximaAccion: 'Adaptar CV', proximaAccionFecha: null }) }); assert.equal(r.body.proximaAccion, 'Adaptar CV'); assert.equal((await request(`/api/candidaturas/${id}`, { method: 'PATCH', body: JSON.stringify({ ofertaId: offer.id }) })).status, 200); const reassigned = await request(`/api/candidaturas/${id}`, { method: 'PATCH', body: JSON.stringify({ ofertaId: state.ofertas[0].id }) }); assert.equal(reassigned.status, 409); assert.match(reassigned.body.error, /vínculo histórico/); assert.equal((await request(`/api/candidaturas/${id}`, { method: 'PATCH', body: JSON.stringify({ estado: 'aceptada' }) })).status, 400); assert.equal((await request(`/api/candidaturas/${id}`, { method: 'DELETE' })).status, 200); }));

test('5. CRUD de eventos validado', async () => withServer('events', async ({ request }) => { const s = (await request('/api/state')).body; const candidate = (await request('/api/candidaturas', post({ ofertaId: s.ofertas[1].id, proximaAccion: '', proximaAccionFecha: null }))).body; let r = await request('/api/eventos', post({ candidaturaId: candidate.id, tipo: 'contacto', fecha: '2028-02-29', nota: 'Llamada breve' })); assert.equal(r.status, 201); const id = r.body.id; r = await request(`/api/eventos/${id}`, { method: 'PATCH', body: JSON.stringify({ nota: 'Llamada de seguimiento', candidaturaId: candidate.id }) }); assert.equal(r.body.nota, 'Llamada de seguimiento'); let conflict = await request(`/api/eventos/${id}`, { method: 'PATCH', body: JSON.stringify({ candidaturaId: s.candidaturas[0].id }) }); assert.equal(conflict.status, 409); assert.match(conflict.body.error, /vínculo histórico/); assert.equal((await request('/api/eventos', post({ candidaturaId: candidate.id, tipo: 'nota', fecha: '2026-02-31', nota: 'Fecha imposible' }))).status, 400); assert.equal((await request('/api/eventos', post({ candidaturaId: candidate.id, tipo: 'nota', fecha: '2027-02-29', nota: 'No bisiesto' }))).status, 400); assert.equal((await request('/api/eventos', post({ candidaturaId: randomUUID(), tipo: 'nota', fecha: '2026-09-23', nota: 'Sin candidatura' }))).status, 400); assert.equal((await request(`/api/eventos/${id}`, { method: 'DELETE' })).status, 200); assert.equal((await request(`/api/candidaturas/${candidate.id}`, { method: 'DELETE' })).status, 200); }));

test('6. fórmulas, score y comparabilidad autoritativos', () => { const p = SEED.perfiles[0], annual = engine.calculateOffer(p, SEED.ofertas[0]), monthly = engine.calculateOffer(p, { ...SEED.ofertas[0], tipoRemuneracion: 'mensual', importeCent: 100000, pagasAnuales: 14 }), hourly = engine.calculateOffer(p, SEED.ofertas[2]); assert.equal(annual.monthlyGrossCent, 200000); assert.equal(annual.variableCostCent, 5850); assert.equal(annual.effectiveMinutesWeek, 2700); assert.equal(annual.effectiveHourValueCent, Math.floor((194150 * 60 * 12 / (2700 * 52)) + .5)); assert.equal(monthly.monthlyGrossCent, 116667); assert.equal(hourly.monthlyGrossCent, 121333); assert.ok(Object.values(annual.dimensions).every(x => x >= 0 && x <= 100)); assert.ok(annual.totalScore >= 0 && annual.totalScore <= 100); const impossible = engine.calculateOffer(p, { ...SEED.ofertas[0], costesFijosMensualesCent: 9999999 }); assert.equal(impossible.effectiveHourValueCent, 0); assert.equal(engine.validateComparableOffers(SEED.ofertas.slice(0, 2)).ok, true); const otherProfileOffer = { ...SEED.ofertas[1], id: randomUUID(), perfilId: randomUUID() }, mixed = engine.validateComparableOffers([SEED.ofertas[0], otherProfileOffer]); assert.equal(mixed.ok, false); assert.match(mixed.reason, /mismo perfil/); });

test('7. alertas jerárquicas, fechas de acción e inactividad real', () => { const hierarchy = createSeed(), severe = hierarchy.ofertas[1]; hierarchy.ofertas = [severe]; hierarchy.candidaturas = []; hierarchy.eventos = []; severe.costesFijosMensualesCent = 9999999; severe.minutosPagadosSemana = 4300; severe.minutosDesplazamientoDia = 130; severe.fechaLimite = null; severe.updatedAt = '2026-09-23T12:00:00Z'; const analysis = engine.analytics(hierarchy, { q: 'Atención', modalidad: 'presencial', estado: 'activa' }, new Date('2026-09-23T13:00:00Z')); assert.deepEqual(analysis.filteredIds, [severe.id]); assert.deepEqual(analysis.alerts.map(a => a.code), ['costes_superan', 'mas_70h', 'desplazamiento_doble', 'sin_candidatura']); assert.equal(analysis.kpis.alertasPrioritarias, 3);
  const lowValue = createSeed(), lowOffer = lowValue.ofertas[0]; lowValue.ofertas = [lowOffer]; lowValue.candidaturas = []; lowValue.eventos = []; lowOffer.costesFijosMensualesCent = 30000; lowOffer.fechaLimite = null; const lowAnalysis = engine.analytics(lowValue, {}, new Date('2026-09-23T13:00:00Z')); assert.ok(lowAnalysis.calculations[0].availableCent > 0); assert.ok(lowAnalysis.calculations[0].effectiveHourValueCent < lowValue.perfiles[0].objetivoHoraCent * 0.75); assert.deepEqual(lowAnalysis.alerts.map(a => a.code), ['valor_75', 'sin_candidatura']); assert.equal(lowAnalysis.kpis.alertasPrioritarias, 1);
  const activity = createSeed(), offer = activity.ofertas[0], recentEventCandidate = { ...activity.candidaturas[0], ofertaId: offer.id, updatedAt: '2026-08-01T00:00:00Z', proximaAccionFecha: '2026-09-22' }, inactive = { ...activity.candidaturas[1], id: randomUUID(), ofertaId: offer.id, updatedAt: '2026-08-01T00:00:00Z', proximaAccionFecha: '2026-09-24' }; activity.ofertas = [offer]; activity.candidaturas = [recentEventCandidate, inactive]; activity.eventos = [{ ...activity.eventos[0], candidaturaId: recentEventCandidate.id, fecha: '2030-01-01', createdAt: '2026-09-23T10:00:00Z' }]; const alerts = engine.buildAlerts(activity, new Date('2026-09-23T12:00:00Z')); assert.ok(alerts.some(a => a.candidatureId === recentEventCandidate.id && a.code === 'accion_vencida')); assert.ok(!alerts.some(a => a.candidatureId === recentEventCandidate.id && a.code === 'accion_48h')); assert.ok(!alerts.some(a => a.candidatureId === recentEventCandidate.id && a.code === 'sin_actualizar_14d')); assert.ok(alerts.some(a => a.candidatureId === inactive.id && a.code === 'accion_48h')); assert.ok(alerts.some(a => a.candidatureId === inactive.id && a.code === 'sin_actualizar_14d')); });

test('8. transiciones e historial inmutable', async () => withServer('transitions', async ({ request }) => { const s = (await request('/api/state')).body, c = (await request('/api/candidaturas', post({ ofertaId: s.ofertas[1].id, proximaAccion: '', proximaAccionFecha: null }))).body; assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'aceptada' }))).status, 409); assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'enviada' }))).status, 200); assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'entrevista' }))).status, 200); assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'entrevista' }))).status, 409); const again = await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'entrevista', evento: { tipo: 'entrevista', fecha: '2026-09-24', nota: 'Segunda entrevista' } })); assert.equal(again.status, 200); assert.equal(again.body.evento.tipo, 'entrevista'); assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'oferta_recibida' }))).status, 200); assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'aceptada' }))).status, 200); assert.equal((await request(`/api/candidaturas/${c.id}/transicion`, post({ a: 'retirada' }))).status, 409); const after = (await request('/api/state')).body; assert.equal(after.historial.filter(h => h.entidadId === c.id && h.accion === 'transicion').length, 5); assert.equal((await request('/api/historial/falso', { method: 'DELETE' })).status, 404); }));

test('9. conflictos, referencias y contrato estricto', async () => withServer('conflicts', async ({ request }) => { const s = (await request('/api/state')).body; assert.equal((await request(`/api/perfiles/${s.perfiles[0].id}`, { method: 'DELETE' })).status, 409); assert.equal((await request(`/api/ofertas/${s.ofertas[0].id}`, { method: 'DELETE' })).status, 409); assert.equal((await request(`/api/candidaturas/${s.candidaturas[0].id}`, { method: 'DELETE' })).status, 409); assert.equal((await request('/api/ofertas', post({ ...offerBody(s.perfiles[0].id), desconocido: true }))).status, 400); assert.equal((await request(`/api/ofertas/${randomUUID()}`)).status, 404); assert.equal((await request(`/api/candidaturas/${s.candidaturas[0].id}/transicion`, post({ a: 'entrevista', extra: true }))).status, 400); }));

test('10. calendario, atomicidad, backup y recuperación conservadora', async () => { const invalidDay = createSeed(); invalidDay.ofertas[0].fechaLimite = '2026-02-31'; assert.equal(validState(invalidDay), false); const leap = createSeed(); leap.ofertas[0].fechaLimite = '2028-02-29'; assert.equal(validState(leap), true); const nonLeap = createSeed(); nonLeap.ofertas[0].fechaLimite = '2027-02-29'; assert.equal(validState(nonLeap), false); const dir = testDir('storage'); try { let store = createStore(dir); const original = store.read(); store.update(s => { s.perfiles[0].nombre = 'Cambio'; }); assert.equal(JSON.parse(fs.readFileSync(store.paths.backup, 'utf8')).perfiles[0].nombre, original.perfiles[0].nombre); assert.equal(fs.readdirSync(dir).filter(x => x.endsWith('.tmp')).length, 0); fs.writeFileSync(store.paths.file, '{principal roto', 'utf8'); const server = createApp({ dataDir: dir }); await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); }); const health = await fetch(`http://127.0.0.1:${server.address().port}/api/health`).then(r => r.json()); await new Promise(resolve => server.close(resolve)); assert.equal(health.recovered, true); store = createStore(dir); assert.equal(store.read().perfiles[0].nombre, original.perfiles[0].nombre); assert.ok(fs.readdirSync(dir).some(x => x.includes('.corrupt-'))); fs.writeFileSync(store.paths.file, '{roto', 'utf8'); fs.writeFileSync(store.paths.backup, '{respaldo roto', 'utf8'); assert.throws(() => createApp({ dataDir: dir }), /Datos ilegibles/); assert.equal(fs.readFileSync(store.paths.file, 'utf8'), '{roto'); assert.equal(fs.readFileSync(store.paths.backup, 'utf8'), '{respaldo roto'); } finally { safeRemove(dir); if (fs.existsSync(ROOT) && fs.readdirSync(ROOT).length === 0) fs.rmdirSync(ROOT); } });
