'use strict';
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { randomUUID, createHash } = require('node:crypto');
const { createStore, ValidationError } = require('./storage.cjs');
const engine = require('./engine.js');
const MAX_BODY = 256 * 1024;
const STATIC = new Map([['/', ['index.html', 'text/html; charset=utf-8']], ['/index.html', ['index.html', 'text/html; charset=utf-8']], ['/styles.css', ['styles.css', 'text/css; charset=utf-8']], ['/app.js', ['app.js', 'text/javascript; charset=utf-8']], ['/engine.js', ['engine.js', 'text/javascript; charset=utf-8']]]);
class HttpError extends Error { constructor(status, message) { super(message); this.status = status; } }
class ConflictError extends Error {}
const trim = (value, max, label) => { if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw new ValidationError(`${label}: 1-${max} caracteres.`); return value.trim(); };
const optional = (value, max, label) => { if (value === undefined || value === null) return ''; if (typeof value !== 'string' || value.trim().length > max) throw new ValidationError(`${label}: máximo ${max} caracteres.`); return value.trim(); };
const int = (value, min, max, label) => { const n = Number(value); if (!Number.isInteger(n) || n < min || n > max) throw new ValidationError(`${label}: entero entre ${min} y ${max}.`); return n; };
const validDate = (value, nullable, label) => { if ((value === null || value === '') && nullable) return null; if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new ValidationError(`${label}: fecha real AAAA-MM-DD.`); const [year, month, day] = value.split('-').map(Number), parsed = new Date(Date.UTC(year, month - 1, day)); if (parsed.getUTCFullYear() !== year || parsed.getUTCMonth() !== month - 1 || parsed.getUTCDate() !== day) throw new ValidationError(`${label}: fecha real AAAA-MM-DD.`); return value; };
const FIELDS = {
  perfiles: ['nombre', 'objetivoHoraCent', 'maxMinutosEfectivosSemana', 'maxDesplazamientoDia', 'pesos'],
  ofertas: ['perfilId', 'empresa', 'puesto', 'ubicacion', 'modalidad', 'tipoRemuneracion', 'importeCent', 'pagasAnuales', 'minutosPagadosSemana', 'minutosNoRemuneradosSemana', 'diasPresenciales', 'minutosDesplazamientoDia', 'costeDesplazamientoDiaCent', 'costesFijosMensualesCent', 'estabilidad', 'flexibilidad', 'accesibilidad', 'fechaLimite', 'estado', 'notas'],
  candidaturas: ['ofertaId', 'proximaAccion', 'proximaAccionFecha'], eventos: ['candidaturaId', 'tipo', 'fecha', 'nota']
};
function strict(body, allowed) { const unknown = Object.keys(body).filter(key => !allowed.includes(key)); if (unknown.length) throw new ValidationError(`Propiedades no permitidas: ${unknown.join(', ')}.`); }
function exists(state, key, id, label) { if (!state[key].some(x => x.id === id)) throw new ValidationError(`${label} no válido.`); return id; }
function find(state, key, id) { const item = state[key].find(x => x.id === id); if (!item) throw new HttpError(404, 'No encontrado.'); return item; }
function history(state, entity, entityId, action, detail) { state.historial.push({ id: randomUUID(), entidad: entity, entidadId: entityId, accion: action, detalle: String(detail || '').slice(0, 300), at: new Date().toISOString() }); }
function profileInput(body) { if (!body.pesos || typeof body.pesos !== 'object' || Array.isArray(body.pesos)) throw new ValidationError('Pesos no válidos.'); strict(body.pesos, ['economia', 'tiempo', 'estabilidad', 'flexibilidad', 'accesibilidad']); const pesos = Object.fromEntries(['economia', 'tiempo', 'estabilidad', 'flexibilidad', 'accesibilidad'].map(k => [k, int(body.pesos[k], 0, 100, `Peso ${k}`)])); if (Object.values(pesos).reduce((a, b) => a + b, 0) !== 100) throw new ValidationError('Los pesos deben sumar 100.'); return { nombre: trim(body.nombre, 80, 'Nombre'), objetivoHoraCent: int(body.objetivoHoraCent, 1, 1000000, 'Objetivo/hora'), maxMinutosEfectivosSemana: int(body.maxMinutosEfectivosSemana, 1, 10080, 'Máximo semanal'), maxDesplazamientoDia: int(body.maxDesplazamientoDia, 0, 1440, 'Máximo desplazamiento'), pesos }; }
function offerInput(body, state) { exists(state, 'perfiles', body.perfilId, 'Perfil'); if (!['presencial', 'hibrida', 'remota'].includes(body.modalidad)) throw new ValidationError('Modalidad no válida.'); if (!['anual', 'mensual', 'hora'].includes(body.tipoRemuneracion)) throw new ValidationError('Remuneración no válida.'); if (!['activa', 'archivada'].includes(body.estado)) throw new ValidationError('Estado de oferta no válido.'); return { perfilId: body.perfilId, empresa: trim(body.empresa, 100, 'Empresa'), puesto: trim(body.puesto, 100, 'Puesto'), ubicacion: trim(body.ubicacion, 100, 'Ubicación'), modalidad: body.modalidad, tipoRemuneracion: body.tipoRemuneracion, importeCent: int(body.importeCent, 0, 1000000000, 'Importe'), pagasAnuales: int(body.pagasAnuales, 1, 24, 'Pagas'), minutosPagadosSemana: int(body.minutosPagadosSemana, 1, 10080, 'Minutos pagados'), minutosNoRemuneradosSemana: int(body.minutosNoRemuneradosSemana, 0, 10080, 'Minutos no remunerados'), diasPresenciales: int(body.diasPresenciales, 0, 7, 'Días presenciales'), minutosDesplazamientoDia: int(body.minutosDesplazamientoDia, 0, 1440, 'Desplazamiento'), costeDesplazamientoDiaCent: int(body.costeDesplazamientoDiaCent, 0, 10000000, 'Coste desplazamiento'), costesFijosMensualesCent: int(body.costesFijosMensualesCent, 0, 100000000, 'Costes fijos'), estabilidad: int(body.estabilidad, 0, 5, 'Estabilidad'), flexibilidad: int(body.flexibilidad, 0, 5, 'Flexibilidad'), accesibilidad: int(body.accesibilidad, 0, 5, 'Accesibilidad'), fechaLimite: validDate(body.fechaLimite, true, 'Fecha límite'), estado: body.estado, notas: optional(body.notas, 1000, 'Notas') }; }
function candidateInput(body, state) { return { ofertaId: exists(state, 'ofertas', body.ofertaId, 'Oferta'), proximaAccion: optional(body.proximaAccion, 200, 'Próxima acción'), proximaAccionFecha: validDate(body.proximaAccionFecha, true, 'Fecha de próxima acción') }; }
function eventInput(body, state) { exists(state, 'candidaturas', body.candidaturaId, 'Candidatura'); if (!['envio', 'contacto', 'entrevista', 'prueba', 'oferta', 'nota', 'otro'].includes(body.tipo)) throw new ValidationError('Tipo de evento no válido.'); return { candidaturaId: body.candidaturaId, tipo: body.tipo, fecha: validDate(body.fecha, false, 'Fecha'), nota: trim(body.nota, 500, 'Nota') }; }
function send(res, status, body) { const data = Buffer.from(JSON.stringify(body)); res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': data.length }); res.end(data); }
function readBody(req) { if ((req.headers['content-type'] || '').split(';')[0].trim().toLowerCase() !== 'application/json') { req.resume(); throw new HttpError(415, 'Envía application/json.'); } return new Promise((resolve, reject) => { const chunks = []; let size = 0, done = false; req.on('data', chunk => { if (done) return; size += chunk.length; if (size > MAX_BODY) { done = true; reject(new HttpError(413, 'Cuerpo demasiado grande.')); req.resume(); } else chunks.push(chunk); }); req.on('end', () => { if (done) return; try { const body = JSON.parse(Buffer.concat(chunks).toString('utf8')); if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error(); resolve(body); } catch { reject(new HttpError(400, 'JSON no válido.')); } }); req.on('error', () => reject(new HttpError(400, 'Petición interrumpida.'))); }); }

function createApp({ dataDir = path.join(__dirname, 'data') } = {}) {
  const resolved = path.resolve(dataDir), store = createStore(resolved);
  const server = http.createServer(async (req, res) => {
    res.setHeader('Cache-Control', 'no-store'); res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('X-Frame-Options', 'DENY'); res.setHeader('Referrer-Policy', 'no-referrer'); res.setHeader('Permissions-Policy', 'camera=(), geolocation=(), microphone=()'); res.setHeader('Cross-Origin-Resource-Policy', 'same-origin'); res.setHeader('Content-Security-Policy', "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
    try {
      const port = server.address().port; if (req.headers.host !== `127.0.0.1:${port}`) throw new HttpError(403, 'Acceso permitido solo mediante 127.0.0.1.'); const url = new URL(req.url, `http://127.0.0.1:${port}`);
      if (req.method === 'GET' && url.pathname === '/api/health') return send(res, 200, { app: 'ofertajusta-local', instance: createHash('sha256').update(resolved.toLowerCase()).digest('hex').slice(0, 16), recovered: store.recovered });
      if (req.method === 'GET' && url.pathname === '/api/state') { const state = store.read(); return send(res, 200, { ...state, analytics: engine.analytics(state, { q: url.searchParams.get('q') || '', modalidad: url.searchParams.get('modalidad') || '', estado: url.searchParams.get('estado') || '', candidaturaEstado: url.searchParams.get('candidaturaEstado') || '' }) }); }
      const calculation = url.pathname.match(/^\/api\/ofertas\/([^/]+)\/calculo$/); if (calculation && req.method === 'GET') { const state = store.read(), offer = find(state, 'ofertas', calculation[1]), profile = find(state, 'perfiles', offer.perfilId); return send(res, 200, engine.calculateOffer(profile, offer)); }
      const transition = url.pathname.match(/^\/api\/candidaturas\/([^/]+)\/transicion$/); if (transition && req.method === 'POST') { const body = await readBody(req); strict(body, ['a', 'evento']); const changed = store.update(state => { const candidate = find(state, 'candidaturas', transition[1]), target = body.a; if (typeof target !== 'string' || !engine.canTransition(candidate.estado, target)) throw new ConflictError(`No se permite pasar de ${candidate.estado} a ${target || 'vacío'}.`); if (candidate.estado === 'entrevista' && target === 'entrevista' && !body.evento) throw new ConflictError('Otra entrevista requiere un evento nuevo.'); const from = candidate.estado, now = new Date().toISOString(); candidate.estado = target; candidate.updatedAt = now; let event = null; if (body.evento) { strict(body.evento, ['tipo', 'fecha', 'nota']); const values = eventInput({ ...body.evento, candidaturaId: candidate.id }, state); event = { id: randomUUID(), ...values, createdAt: now }; state.eventos.push(event); } history(state, 'candidaturas', candidate.id, 'transicion', `${from} → ${target}`); return { candidatura: candidate, evento: event }; }); return send(res, 200, changed); }
      const collection = url.pathname.match(/^\/api\/(perfiles|ofertas|candidaturas|eventos)$/);
      if (collection && req.method === 'GET') return send(res, 200, store.read()[collection[1]]);
      if (collection && req.method === 'POST') { const body = await readBody(req), key = collection[1]; strict(body, FIELDS[key]); const created = store.update(state => { const now = new Date().toISOString(); let item; if (key === 'perfiles') item = { id: randomUUID(), ...profileInput(body), createdAt: now, updatedAt: now }; if (key === 'ofertas') item = { id: randomUUID(), ...offerInput(body, state), createdAt: now, updatedAt: now }; if (key === 'candidaturas') item = { id: randomUUID(), ...candidateInput(body, state), estado: 'borrador', createdAt: now, updatedAt: now }; if (key === 'eventos') item = { id: randomUUID(), ...eventInput(body, state), createdAt: now }; state[key].push(item); history(state, key, item.id, 'creado', item.nombre || item.puesto || item.nota || 'Registro creado'); return item; }); return send(res, 201, created); }
      const member = url.pathname.match(/^\/api\/(perfiles|ofertas|candidaturas|eventos)\/([^/]+)$/);
      if (member && ['GET', 'PATCH', 'DELETE'].includes(req.method)) { const [, key, id] = member; if (req.method === 'GET') return send(res, 200, find(store.read(), key, id)); if (req.method === 'PATCH') { const body = await readBody(req); strict(body, FIELDS[key]); const changed = store.update(state => { const item = find(state, key, id); if (key === 'candidaturas' && body.ofertaId !== undefined && body.ofertaId !== item.ofertaId) throw new ConflictError('La oferta de una candidatura es un vínculo histórico y no se puede cambiar.'); if (key === 'eventos' && body.candidaturaId !== undefined && body.candidaturaId !== item.candidaturaId) throw new ConflictError('La candidatura de un evento es un vínculo histórico y no se puede cambiar.'); let values; if (key === 'perfiles') values = profileInput({ ...item, ...body }); if (key === 'ofertas') values = offerInput({ ...item, ...body }, state); if (key === 'candidaturas') values = candidateInput({ ...item, ...body }, state); if (key === 'eventos') values = eventInput({ ...item, ...body }, state); Object.assign(item, values); if (key !== 'eventos') item.updatedAt = new Date().toISOString(); history(state, key, id, 'editado', item.nombre || item.puesto || item.nota || 'Registro editado'); return item; }); return send(res, 200, changed); }
        const deleted = store.update(state => { const item = find(state, key, id); if (key === 'perfiles' && state.ofertas.some(x => x.perfilId === id)) throw new ConflictError('El perfil tiene ofertas asociadas.'); if (key === 'ofertas' && state.candidaturas.some(x => x.ofertaId === id)) throw new ConflictError('La oferta tiene candidaturas asociadas.'); if (key === 'candidaturas' && state.eventos.some(x => x.candidaturaId === id)) throw new ConflictError('La candidatura tiene eventos asociados.'); state[key].splice(state[key].indexOf(item), 1); history(state, key, id, 'eliminado', item.nombre || item.puesto || item.nota || 'Registro eliminado'); return item; }); return send(res, 200, { ok: true, deleted }); }
      if (['GET', 'HEAD'].includes(req.method) && STATIC.has(url.pathname)) { const [file, type] = STATIC.get(url.pathname), content = fs.readFileSync(path.join(__dirname, 'public', file)); res.writeHead(200, { 'Content-Type': type, 'Content-Length': content.length }); return res.end(req.method === 'HEAD' ? undefined : content); }
      throw new HttpError(404, 'No encontrado.');
    } catch (error) { const status = error instanceof HttpError ? error.status : error instanceof ConflictError ? 409 : error instanceof ValidationError ? 400 : 500; if (status === 500) console.error(error); if (!res.destroyed) send(res, status, { error: status === 500 ? 'Error interno.' : error.message }); }
  });
  return server;
}
if (require.main === module) { const port = process.env.OFERTAJUSTA_PORT === undefined ? 4327 : Number(process.env.OFERTAJUSTA_PORT), app = createApp({ dataDir: process.env.OFERTAJUSTA_DATA_DIR || path.join(__dirname, 'data') }); app.on('error', error => { console.error(error.code === 'EADDRINUSE' ? `Puerto ${port} ocupado.` : error.message); process.exitCode = 1; }); app.listen(port, '127.0.0.1', () => console.log(`OfertaJusta en http://127.0.0.1:${port}\nCtrl+C para cerrar.`)); }
module.exports = { createApp };
